// Array de productos
const productsData = [
    {
      id: 1,
      name: "La Mr. Pit",
      description: "Solo para expertos",
      price: "$ 350",
      category: "pizzas",
      cardImg: ".\images\popular\La Mr. Pit.png", 
      popular: true ,
    },
    {
        id: 2,
        name: "¡Q’ Jamone!",
        description: "c/jamón crudo",
        price: "$ 350",
        category: "pizzas",
        cardImg: ".images\popular\¡Q’ Jamone!.png",
        popular: true ,
      },
      {
        id: 3,
        name: "La Charly García",
        description: "¡BASTA!",
        price: "$ 380",
        category: "pizzas",
        cardImg: ".images\popular\La Charly García.png",
        popular: true ,
      },
      {
        id: 4,
        name: "La Maradona",
        description: "¡Eterna!",
        price: "$ 450",
        category: "pizzas",
        cardImg: ".images\popular\La Maradona.png",
        popular: true ,
      },
      {
        id: 5,
        name: "Picantovich",
        description: "Pica 2 veces",
        price: "$ 750",
        category: "pizzas",
        cardImg: ".images\popular\Picantovich.png",
        popular: true,
      },
      {
        id: 6,
        name: "La Hasbulla",
        description: "En honor al 1",
        price: "$ 990",
        category: "pizzas",
        cardImg: ".images\popular\La Hasbulla.png",
        popular: true ,
      },
      {
        id: 7,
        name: "Leo Messi",
        description: "¡De pié señores!",
        price: "$ 10",
        category: "pizzas",
        cardImg: ".images\popular\Leo Messi.png",
        popular: true ,
      },
      {
        id: 8,
        name: "Nick Gi",
        description: "La que desaparece",
        price: "$ Gratis",
        category: "pizzas",
        cardImg: ".images\popular\Nick Gi.png",
        popular: true,
      },
      {
        id: 9,
        name: "Americana",
        description: "Sentite Yankiee",
        price: "$400",
        category: "burgers",
        cardImg: ".images\burgers\americana.jpeg",
        popular: false ,
      },
      {
        id: 10,
        name: "BOOM",
        description: "Explotá de sabores",
        price: "$500",
        category: "burgers",
        cardImg: ".images\burgers\boom.jpeg",
        popular: false,
      },
      {
        id: 11,
        name: "De la Casa",
        description: "Un halago",
        price: "$400",
        category: "burgers",
        cardImg: ".images\burgers\delacasa.jpeg",
        popular: false,
      },
      {
        id: 12,
        name: "TapaArterias",
        description: "Para tres",
        price: "$600",
        category: "burgers",
        cardImg: ".images\burgers\tapaarterias.jpeg",
        popular: false ,
      },
      {
        id: 13,
        name: "Cara de Papa",
        description: "Terrible" ,
        price: "$600",
        category: "papas",
        cardImg: ".images\papas\caradepapa.jpeg",
        popular: false,
      },
      {
        id: 14,
        name: "Metele Huevos",
        description: "Como en la vida",
        price: "$700",
        category: "papas",
        cardImg: ".images\papas\metelehuevos.jpg",
        popular: false ,
      },
      {
        id: 15,
        name: "Que Peregil",
        description: "Probala, no seas gil.",
        price: "$700",
        category: "papas",
        cardImg: ".images\papas\queperegil.jpeg",
        popular: false,
      },
      {
        id: 16,
        name: "Que sabores",
        description: "Un Plagio a Knorr",
        price: "$690",
        category: "papas",
        cardImg: ".images\papas\quesabor.jpg",
        popular: false,
      },
      {
        id: 17,
        name: "Banana",
        description: "Inspirado en Minions",
        price: "$500",
        category: "batidos",
        cardImg: ".images\batidos\banana.jpeg",
        popular: false,
      },
      {
        id: 18,
        name: "Griego",
        description: "Frambuesa y Yogurt",
        price: "$450",
        category: "batidos",
        cardImg: ".images\batidos\batido-de-frambuesa-y-yogur.jpg",
        popular: false ,
      },
      {
        id: 19,
        name: "Chocolate",
        description: "Nada que aclarar",
        price: "$500",
        category: "batidos",
        cardImg: ".images\batidos\chocolate.jpeg",
        popular: false,
      },
      {
        id: 20,
        name: "Naranja",
        description: "Este si es natural 100%",
        price: "$400",
        category: "batidos",
        cardImg: ".images\batidos\naranja.jpeg",
        popular: false ,
      },
  ];
  